### ISSUE TITLE
Content in English

### ISSUE THREAD

**Issue by aleon1220** [alesaudate/soa#2]
Have you considered expanding content in another repo or branch in English?
i can help with the translation I speak English spanish and portuguese

**Comment by aleon1220** [comment]
@alesaudate  any way i can help man???

**Comment by alesaudate** [comment]
Hi Andres, how are you doing ?

Unfortunately,  this is not up to me to decide. It's much more on CdC.

But anyway, we're just about to retire this book (getting it off the
catalogue), therefore I don't believe this proposal would be accepted.

Regards,
Alexandre Saudate

Em qua, 8 de abr de 2020 21:46, Andres Leon Rangel <notifications@github.com>
escreveu:

**Comment by aleon1220** [comment]
i am so sorry to hear that. Books like this are useful to have strong foundation on an architecture that can still be used in some companies. Not everything has to be microservices or serverless...
